---
- name: Install and configure Zabbix agent
  hosts: all
  become: yes
  gather_facts: yes

  tasks:

    - name: Check if zabbix_server_ip is set
      fail:
        msg: "The variable 'zabbix_server_ip' is not set. Please set this variable."
      when: zabbix_server_ip is not defined or zabbix_server_ip == "" or zabbix_server_ip is none


    - name: Install Zabbix repository
      become: yes
      shell: rpm -Uvh https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-2.el9.noarch.rpm
      args:
        creates: /etc/yum.repos.d/zabbix.repo
      when: ansible_os_family == 'RedHat'

    - name: Clean DNF cache
      become: yes
      dnf:
        update_cache: true
        state: present
      when: ansible_os_family == 'RedHat'


    - name: Install Zabbix repository
      become: yes
      shell:
        cmd: wget https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu20.04_all.deb && dpkg -i zabbix-release_6.4-1+ubuntu20.04_all.deb
        chdir: /tmp
      args:
        creates: /etc/apt/sources.list.d/zabbix.list
      when: ansible_os_family == 'Debian'

    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'


    - name: Install Zabbix agent2
      become: yes
      ansible.builtin.package:
        name: zabbix-agent2,zabbix-agent2-plugin-*
        state: present

    - name: Configure Zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^Server='
        line: 'Server={{ zabbix_server_ip }}'
        state: present
      notify:
        - restart zabbix-agent

    - name: Start and enable Zabbix agent2
      become: yes
      systemd:
        name: zabbix-agent2
        state: started
        enabled: yes

  handlers:
    - name: restart zabbix-agent
      service:
        name: zabbix-agent2
        state: restarted